version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - .:/app
      - chrome-data:/chrome-data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROME_DEBUG_PORT=9222
      - LINKEDIN_USERNAME=${LINKEDIN_USERNAME}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
    ports:
      - "9222:9222"
    command: scrape

  analyzer:
    build: .
    volumes:
      - .:/app
      - chrome-data:/chrome-data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROME_DEBUG_PORT=9222
    command: analyze
    depends_on:
      - scraper

volumes:
  chrome-data: 